github:
  description: "Apache Sling Distribution Avro Serializer (deprecated)"
  homepage: "https://sling.apache.org/"
  labels:
  - "sling"
  - "deprecated"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
notifications:
  jira_options: "link"
